name: Auto Share File in Google Drive
run-name: ${{ github.actor }} is sharing file by using crontab ğŸš€
on: 
  schedule: 
    - cron: '48 15 * * *'

jobs:
  Start-Daily-Actions:
    runs-on: macos-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Decode token.json
        run: |
          echo "${{ secrets.TOKEN_JSON }}" | base64 -d > token.json
      - name: Decode files_information.py
        run: |
          echo "${{ secrets.FILES_INFORMATION_PY }}" | base64 -d > ./Sharely/files_information.py
      - name: Create data file
        run: |
          mkdir data
      - name: Excecute list_filename.py
        run: |
          ./venv/bin/python3 ./test/list_filename.py 
      - run: echo "ğŸ This job's status is ${{ job.status }}."
